// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaCasa.Infra.Context;

namespace MinhaCasa.Infra.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200819202104_inical")]
    partial class inical
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MinhaCasa.Domain.NaoContemplados.Entities.Familia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoriaDependente")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaIdadePretendente")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaRenda")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeCriteriosAtendidos")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Familia");
                });

            modelBuilder.Entity("MinhaCasa.Domain.NaoContemplados.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoVinculoFamiliar")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("MinhaCasa.Domain.NaoContemplados.Entities.ProcessosSelecao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.ToTable("ProcessoSelecao");
                });

            modelBuilder.Entity("MinhaCasa.Domain.NaoContemplados.Entities.Pessoa", b =>
                {
                    b.HasOne("MinhaCasa.Domain.NaoContemplados.Entities.Familia", "Familia")
                        .WithMany("Pessoas")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MinhaCasa.Domain.NaoContemplados.ValuesObjects.Renda", "Renda", b1 =>
                        {
                            b1.Property<Guid>("PessoaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasColumnName("ValorRenda")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("PessoaId");

                            b1.ToTable("Pessoa");

                            b1.WithOwner("Pessoa")
                                .HasForeignKey("PessoaId");
                        });
                });

            modelBuilder.Entity("MinhaCasa.Domain.NaoContemplados.Entities.ProcessosSelecao", b =>
                {
                    b.HasOne("MinhaCasa.Domain.NaoContemplados.Entities.Familia", "Familia")
                        .WithMany("ProcessosSelecao")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
