// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaCasa.Infra.Context;

namespace MinhaCasa.Infra.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MinhaCasa.Domain.NaoContemplados.Entities.Familia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("CategoriaDependente")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("CategoriaIdadePretendente")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("CategoriaRenda")
                        .HasColumnType("SMALLINT");

                    b.Property<int>("Pontuacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(2)
                        .HasDefaultValue(0);

                    b.Property<short>("QuantidadeCriteriosAtendidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLINT")
                        .HasDefaultValue((short)0);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Familia");
                });

            modelBuilder.Entity("MinhaCasa.Domain.NaoContemplados.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<short>("TipoVinculoFamiliar")
                        .HasColumnType("SMALLINT");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("Id");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("MinhaCasa.Domain.NaoContemplados.Entities.ProcessosSelecao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.ToTable("ProcessoSelecao");
                });

            modelBuilder.Entity("MinhaCasa.Domain.NaoContemplados.Entities.Pessoa", b =>
                {
                    b.HasOne("MinhaCasa.Domain.NaoContemplados.Entities.Familia", "Familia")
                        .WithMany("Pessoas")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MinhaCasa.Domain.NaoContemplados.ValuesObjects.Renda", "Renda", b1 =>
                        {
                            b1.Property<Guid>("PessoaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasColumnName("ValorRenda")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("PessoaId");

                            b1.ToTable("Rendas");

                            b1.WithOwner()
                                .HasForeignKey("PessoaId");
                        });
                });

            modelBuilder.Entity("MinhaCasa.Domain.NaoContemplados.Entities.ProcessosSelecao", b =>
                {
                    b.HasOne("MinhaCasa.Domain.NaoContemplados.Entities.Familia", "Familia")
                        .WithMany("ProcessosSelecao")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
